site_name: "Nichtlineare Optimierung ohne Nebenbedingungen: Mehrdimensionale Verfahren"
pages:
- Home: index.md
- 'Nelder-Mead Verfahren': nmo.md
- 'Gradientenverfahren': gradienten.md
- 'Koordinatenabstiegsmethode': koordinatenabstieg.md
theme: readthedocs
