coordesc: main.cpp coordesc_optimizer.hpp point.hpp pipe.hpp gnuplotter.hpp Funktion.h Funktion.cpp
	g++ -std=c++11 -o coordesc main.cpp Funktion.cpp -Wno-unused-parameter -Wextra -Wall

clean:
	rm coordesc
